export const DEPARTMENTS = [
  "Computer Science",
  "Pharmacy",
  "HR",
  "Law",
  "Public Health",
  "Nursing",
  "Accounting",
  "Marketing",
  "Banking & Finance",
  "Psychology",
  "Architecture",
  "IT",
  "Civil Engineering",
  "Communications",
  "Management",
  "Fashion Design",
  "Interior Design",
  "Real Estate",
  "University-Wide",
];
